# -*- coding: utf-8 -*-
"""Average form input  file with exception handling.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Cxm_OXLCcvfqHF8pUonIeVUEGX0n_7VQ
"""

def get_values_from_file(filename, line):

  try:
    with open(filename, 'r') as file:
      for line in file:
        if line not in file:
          raise Exception (f"'{line}'not found in the file.")
      print(f"{line} is found in the file")
  except FileNotFoundError:
    print("files not found")

    print("")

get_values_from_file("name.txt", "sam")