# -*- coding: utf-8 -*-
"""Calculate weekly pay.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rUF07EYSR7LdrazTQBRCwLrdt8qy8jmM
"""

def get_input():
  wage = float(input("Please enter wage: "))
  hours_worked = float(input("Please enter hours worked: "))
  return wage, hours_worked

def weekly_pay(wage, hours_worked):
    if hours_worked > 40:
        regular_pay = wage * 40
        overtime_hours = hours_worked - 40
        overtime_pay = (wage * 1.5) * overtime_hours
        total_pay = regular_pay + overtime_pay
    else:
        total_pay = wage * hours_worked

    print(f"Weekly pay: ${total_pay:.2f}")

def main():
    wage, hours_worked = get_input() # give value to
    weekly_pay(wage, hours_worked)

if __name__ == "__main__":
    main()