# -*- coding: utf-8 -*-
"""ch7-csv-file.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gYHJHqmfFPozO1R1quTinoBneKmEqk3A
"""

# Q1:
# import csv
# categories = []
# values = []

# with open('data.csv', mode='r') as file:
#     reader = csv.reader(file)
#     next(reader)  # skip the header row

#     for row in reader:
#         categories.append(row[0])
#         values.append(int(row[1]))

# print("Categories List:", categories)
# print("Values List:", values)


# Q2:
import csv
import matplotlib.pyplot as plt
categories = []
values = []
colors = ['red', 'green', 'blue', 'cyan', 'black']

with open('data.csv', mode='r') as file:
    reader = csv.reader(file)
    next(reader)

    for row in reader:
        categories.append(row[0])
        values.append(int(row[1]))

plt.bar(categories, values, color=colors)
plt.title('Fruit Distribution')
plt.xlabel('Categories')
plt.ylabel('Value')

plt.show()