# -*- coding: utf-8 -*-
"""Chapter 9 - Sets

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iSaJv8l-6_MZzO-D5mN1lnU_YqDh3KzB
"""

baseball = set(['Jodi','Carmen','Aida','Alicia'])
basketball = set(['Eva','Carmen','Alicia','Sarah'])
# 1.
print("The following students are on the baseball team:", baseball)
# 2.
print("The following students are on the basketball team::", basketball)
# 3.
both = baseball.intersection(basketball)
print("The following students play both baseball and basketball:", both)

# 4.
either = baseball.union(basketball)
print("The following students play either baseball or basketball", either)

# 5.
baseball_only = baseball.difference(basketball)
print("The following students play baseball but not basketball:", baseball_only)

# 6.
basketball_only = basketball.difference(baseball)
print("The following students play basketball but not baseball:", basketball_only)

# 7.
one_sport = baseball.symmetric_difference(basketball)
print("The following students play one sport, but not both:", one_sport)