# -*- coding: utf-8 -*-
"""chapter_8 string.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Hv5l-FtIj_B0CoxhRc8N9frERQYVMxNb
"""

# Q_1:-------------------------------------------
# string = input("Enter a sentence: ")
# count = 0

# for char in string:
#     if char == 'T' or char == 't':
#         count += 1
# print(f"The letter 'T' appears {count} times.")


# Q_2:-----------------------------------------------------
# date = '11/26/2020'
# date_parts = date.split('/')

# month, day, year = date_parts
# print(f"Month: {month}")
# print(f"Day: {day}")
# print(f"Year:{year}")

# Q_3:-------------------------------------------------------
# first_name = input("Enter your first name: ")
# last_name = input("Enter your last name: ")
# student_id = input("Enter your student ID number: ")

# part_1 = first_name[:3]
# part_2 = last_name[:3]
# part_3 = student_id[-3:]

# login_name = part_1 + part_2 + part_3
# print(f"Your system login name is: {login_name}")

# Q_4:----------------------------------------------------
correct_length = False
has_uppercase = False
has_digit = False
has_lowercase = False

password = input("please enter your password: ")

if len(password) >= 7:
    correct_length = True

for char in password:
    if char.isupper():
        has_uppercase = True
    elif char.islower():
        has_lowercase = True
    elif char.isdigit():
        has_digit = True

if correct_length and has_uppercase and has_lowercase and has_digit :
    print("Ture.")
else:
    print("False")