# -*- coding: utf-8 -*-
"""Chapter 9 - dictionaries

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h6OHM4VIIU4M65DpV0zK8XlFr2pJStJ7
"""

# Q1:-----------------
persons = {'Danny':'New York', 'Ben':'New Jersey','Bob':'Chicago', 'Tom':'houston','Sam':'Phoenix','Tim':'Philadelphia','Nancy':'Chicago'}
chicago = [name for name, city in persons.items() if city == 'Chicago']  # *****
print(chicago)

# Q2:----------------
# original = {'Math': 'Alice', 'Science': 'Bob', 'History': 'Charlie',}
# swapped = {value: key for key, value in original.items()}
# print(swapped)

# Q3:------------------
# employees = {
#     'Alice': {'age': 25, 'department': 'Sales'},
#     'Bob': {'age': 30, 'department': 'Marketing'},
#     'Charlie': {'age': 28, 'department': 'Sales'},
#     'Daisy': {'age': 22, 'department': 'IT'},      }

# sales_employees = {name:detail for name, detail in employees.items() if detail['department'] == 'Sales' }
# print(sales_employees)

# Q4.
dict1 = {'a': 10, 'b': 20, 'c': 30}
dict2 = {'b': 15, 'c': 5, 'd': 50}
combined = {}

for key, value in dict1.items():
    combined[key] = value

for key, value in dict2.items():
    if key in combined:
        combined[key] += value
    else:
        combined[key] = value
print(combined)

# Q5.
friend = {}

def main_menu():
    print("Birthday Manager")
    print("1. Add a BirthdaY")
    print("2. View a birthday")
    print("3. Display All Birthdays")
    print("4. Exit")

    choice = input("enter your choice: ")

    if choice == '1':
        add_friend()
    elif choice == '2':
        view_friend()
    elif choice == '3':
        display_all_friends()
    elif choice == '4':
        print("Goodbye!.")


def add_friend():
    name = input("Enter friend's name: ")
    birthday = input("Enter birthday(e.g.,YYYY-MM-DD): ")
    friend[name] = birthday
    print(f"{name}'s birthday has been added.")

def view_friend():
    name = input("Enter the name of the friend whose birthday you want to view: ")
    if name in friend:
        print(f"{name}'s birthday is on {friend[name]}.")

def display_all_friends():
    print("Friends' Birthdays:")
    for name, birthday in friend.items():
        print(name, birthday)

if __name__ == "__main__":
    main_menu()