# -*- coding: utf-8 -*-
"""f_to_c.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dXAvJGEG9Ldfj7NJZwjzvQhn4zYZVgnG
"""

fahrenheit = float(input("Enter the temperature in Fahrenheit: "))

celsius = (5 / 9) * (fahrenheit - 32)

print(f"{fahrenheit} Fahrenheit is equal to {celsius:.2f} Celsius")