# -*- coding: utf-8 -*-
"""file and exception.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S-2ZWcC8_iovURTegYyvYJQfxErpTWz8
"""

# read a file to add numbers
# filename = 'numbers.txt'
# numbers = []
# with open(filename, 'r') as file:
#   for line in file:
#     numbers.append(int(line.strip()))

# total = sum(numbers)
# print("The numbers are:", numbers)
# print("Their total is:", total)



# create records in a file
# filename = 'employee.txt'
# employee_data = []
# num_records = int(input("How many empolyee records do you want to create?"))

# for i in range(num_records):
#   print(f"Enter data for employee #{i+1}:")
#   name = input("Name: ")
#   id = input("ID number: ")
#   department = input("Department: ")
#   employee_data.append(f"{name}, {id}, {department}")

# with open(filename, 'w') as file:
#   file.writelines(employee_data)

# print("Employee records written t employee.txt")



# search a record in a file employee.txt

filename = 'employee.txt'
search_value = input("Enter the name of the employee to search: ")
found = False

with open(filename, 'r') as file:
    for line in file:
        fields = line.strip().split(', ')
        if fields[0] == search_value:
            found = True
            print("Employee Record Found:")
            print("Name:", fields[0])
            print("Age:", fields[1])
            print("Position:", fields[2])
if not found:
    print("Error: No records found matching the name:", search_value)