# -*- coding: utf-8 -*-
"""for loop assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16CvJQgkiatquKFUT2rhwRJyuYtnT9d4q
"""

#Q1.
# vowel = ["a","e","i","o","u"]
# total = 0
# strings = input("please enter your string")
# for items in strings:
#   if items in  vowel:
#     total += 1
# print("there are ",total, "vowel in your strings")


#Q2.----------------------------------------------------------------------------------------
# number = int(input("Please enter a number: "))
# for i in range(11):
#     result = number * i
#     print(f"{number} x {i} = {result}")

#Q3.------------------------------------------------------------------------------------
# student_grades = {
#     'Alice': 85,
#     'Bob': 92,
#     'Charlie': 78,
#     'Diana': 88,
#     'Eva': 91
# }

# for student, grades in student_grades.items():  # .items()--every elements in dictionary
#     print(f"{student}: {grades}")

#Q4.-------------------------------------------------------------------------------
# numbers = [1,2,3,4,5,6,7,8,9,10,]
# even_count = 0
# odd_count = 0
# even_numbers = []
# odd_numbers = []

# for number in numbers:
#     if number % 2 == 0:
#         even_count += 1
#         even_numbers.append(number)
#     else:
#         odd_count += 1
#         odd_numbers.append(number)

# print(f"Total even numbers: {even_count}")
# print(f"Even numbers: {even_numbers}")
# print(f"Total odd numbers: {odd_count}")
# print(f"Odd numbers: {odd_numbers}")

#Q5.----------------------------------------------------------------------------------
numbers = [3,5,7,2,8,-1,4]
largest = numbers[0]
smallest = numbers[0]

for number in numbers:
  if number > largest:
    largest = number
  if number < smallest:
    smallest = number

print(f"Largest number: {largest}")
print(f"Smallest number: {smallest}")

