# -*- coding: utf-8 -*-
"""format_print

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LddrAItOeCuM5nwjjZdeNI4w3U75Wqnz
"""

num1 = 1.8
num2 = 12.9
num3 = 2
num4 = 100.25

print(f"{num1:.2f}")
print(f"{num2:.2f}")
print(f"{num3:.2f}")
print(f"{num4:.2f}")