# -*- coding: utf-8 -*-
"""Four_digit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nZhQlrkrnGghKVUO7G7wZeK0VwjE4arw
"""

four_digit_num = int (input("enter a four_digit integer"))
if 1000 <= four_digit_num <= 9999:
  digit_1 = four_digit_num//1000
  digit_2 = (four_digit_num//100)% 10
  digit_3 =(four_digit_num//10)% 10
  digit_4 = four_digit_num % 10

  sum_digits = digit_1 + digit_2 + digit_3 + digit_4
  print("The individual digits of your input are: ",  digit_1,  digit_2, digit_3, digit_4)
  print("The sum of your input is: ", sum_digits)
else:
  print("Your input was not four digits. Quitting.")