# -*- coding: utf-8 -*-
"""Grade Calculator .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vSFM0faX1FcHtM4EmMZN3yZFQRBjuTSG
"""

total = 0
count = 0
marks = [85,92,78,90,88]
for a in marks:
  total += a
  count +=1
  average = total//count
print(average)

for a in marks:
  if 90<= a <=100:
    print("A")
  elif 80<= a <= 89:
    print("B")
  elif 70<= a <= 79:
    print("C")
  elif 60 <= a <= 69:
    print("D")
  else:
    print("F")