# -*- coding: utf-8 -*-
"""locker combination1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C46LBNPC-RC7y6-EqeKPWpwuqarq3yNq
"""

# Shuyi Li
import random
def lockerCombo():
  myname = "Shuyi"

  num1 = random.randint(0,39)
  num2 = random.randint(0,39)
  num3 = random.randint(0,39)
  if num1 != num2 and num2 != num3:
     print ( f"{myname}'s locker combination is: {num1}-{num2}-{num3}")
  else:
     print("Please try again, this is not a valid combination")
lockerCombo()