# -*- coding: utf-8 -*-
"""math_ops

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1adpDUBp2jlpecvmMBQSv8owPXoZjDKs7
"""

num1 = int(input("Enter the first integer: "))
num2 = int(input("Enter the second integer: "))

sum_ = num1 + num2
difference = num1 - num2
product = num1 * num2
average = (num1 + num2) / 2
distance = abs(difference)
maximum = max(num1, num2)
minimum = min(num1, num2)

print(f"Sum: {sum_}")
print(f"Difference: {difference}")
print(f"Product: {product}")
print(f"Average: {average}")
print(f"Distance: {distance}")
print(f"Maximum: {maximum}")
print(f"Minimum: {minimum}")