# -*- coding: utf-8 -*-
"""modular.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/119UqEfUmvEYeA5QGWwqTFKPzqcD4c2h9
"""

def get_grade():
      grade = float(input("Enter the grade (0-100): "))
      if 0 <= grade <= 100:
           return grade

def letter_grade(percentage_grade):
    if percentage_grade >= 90:
        print("Your letter grade is: A")
    elif percentage_grade >= 80:
        print("Your letter grade is: B")
    elif percentage_grade >= 70:
        print("Your letter grade is: C")
    elif percentage_grade >= 60:
        print("Your letter grade is: D")
    else:
        print("Your letter grade is: F")

def caculate():
    print("Enter grades for three assignments:")
    grades = []
    for i in range(3):
        grades.append(get_grade())
    percentage_grade = sum(grades) / len(grades)
    print(f"Your average percentage grade is: {percentage_grade:.1f}%")

    letter_grade(percentage_grade)


caculate()