# -*- coding: utf-8 -*-
"""name_printer

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oiHZ-XwEyUIfk0EByijXkWEMSyHMe4l_
"""

print("+-----+")
 print("|shuyi|")
 print("+-----+")