# -*- coding: utf-8 -*-
"""print_grid

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KmRNf1hJ5orczNX7iZC67V8Pr6TicMQL
"""

comb_pattern = "+--+--+--+"
bottom_line = "|  |  |  |"
print(comb_pattern)
print(bottom_line)
print(comb_pattern)
print(bottom_line)
print(comb_pattern)
print(bottom_line)
print(comb_pattern)