# -*- coding: utf-8 -*-
"""restaurant

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RgGcT-uJLsGAVM701WooqaeK9amBwebI
"""

vegetarian = False
vegan = False
gluten_free = False

r_1 = input("is anyone in yur party a vegetarian?")
if r_1 =="yes" :
  vegetarian = True

r_2 = input("is anyone in yur party a vegan?")
if r_2 == "yes":
  vegan = True

r_3 = input("is anyone in yur party gluten_free?")
if r_3 == "yes":
  gluten_free = True

if not  vegetarian  and not vegan and not gluten_free :
  print("Joe's Gourmet Burgers")
if not vegan and not gluten_free:
  print("Mama's Fine italian")
if not vegan:
  print("Main Street Pizza")
print("Corner Cafe")
print("Chef's Kitchen")