# -*- coding: utf-8 -*-
"""squares of list elements.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ls5gmgcGwcEdscgVVEAjeJhZPC_ZyQ_m
"""

numbers = [2, 4, 6, 8]
for number in numbers:
    print(number ** 2, end=' ')