# -*- coding: utf-8 -*-
"""String and List Operations in Python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xVij-0_7XGsoNzaAPAkPKJtnemVDUgZB
"""

# Q_1---------------------------------------------------------------
# input_string = input("enter a string")
# cleaned = input_string.replace(" ", "").lower()
# reversed_cleaned = cleaned[::-1]

# if reversed_cleaned == cleaned :
#     print(f'"{input_string}" is a palindrome.')
# else:
#     print(f'"{input_string}" is not a palindrome.')

# Q_2-------------------------------------------------------------
# vowels = "aeiouAEIOU"
# SUM = 0
# input_string = input("Enter a string: ")

# for char in input_string:
#     if char in vowels:
#         SUM += 1
# print(SUM)


# Q_3-----------------------------------------------------------------
# sentence = input("Enter a sentence: ")
# words = sentence.split()
# longest = max(words, key=len)

# print(longest)

# Q_4-------------------------------------------------------------------
# numbers = [3, 5, 2, 9, 6]
# maximum = max(numbers)
# minimum = min(numbers)

# print(f'Maximum {maximum}')
# print(f'Minimum: {minimum}')

# Q_5--------------------------------------------------------------------
# items = [1, 2, 2, 3, 4, 4, 5]
# no_duplicates = list(set(items))

# print(f'List with duplicates removed: {no_duplicates}')

# Q_6--------------------------------------------------------------------- recheck
# numbers = [3, 5, 2, 9, 6]
# even_numbers = []
# odd_numbers = []
# for n in numbers:
#     if n % 2 == 0:
#         even_numbers.append(n)
#     else:
#         odd_numbers.append(n)
# print(f'Even numbers: {even_numbers}')
# print(f'Odd numbers: {odd_numbers}')

# Q_7----------------------------------------------------------------------
# list1 = [1, 2, 3, 4]
# list2 = [3, 4, 5, 6]
# merged = list1 + list2
# unique = list(set(merged))
# unique.sort()
# print(f'Merged and unique list: {unique}')

# Q_8------------------------------------------------------------------------
# list1 = [1, 2, 3, 4]
# list2 = [3, 4, 5, 6]
# set1 = set(list1)
# set2 = set(list2)
# difference = set1 - set2
# difference_list = list(difference)

# print(f'Difference of list1 - list2: {difference_list}')

# Q_9-------------------------------------------------------------------------
# words = ["listen", "enlist", "hello", "world", "drowl"]
# anagrams = []
# for i in range(len(words)):
#   for j in range(i + 1, len(words)): #check from the next item to the end
#     if sorted(words[i]) == sorted(words[j]):
#       anagrams.append((words[i], words[j]))
# print(f'Anagram pairs found: {anagrams}')

# Q_11--------------------------------------------------------------------
# strings = ["Hello", "world", "Python", "rocks"]
# result = "-".join(strings)
# print(f'Joined string: "{result}"')

# Q_12---------------------------------------------------------------------
input_string = "Hello, World! 123"
for char in input_string:
    if not char.isalpha():
        input_string = input_string.replace(char, '')
print(input_string)