# -*- coding: utf-8 -*-
"""Temperature Conversion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OxubYd2zTL9fBguIXkXbedNE1Wh0uSE0
"""

def celsius_to_fahrenheit(celsius):
    return (celsius * 9/5) + 32

def fahrenheit_to_celsius(fahrenheit):
    return (fahrenheit - 32) * 5/9

def main():
    print("1 to convert Celsius to Fahrenheit or '2' to convert Fahrenheit to celsius:")
    while True:
        choice = input("Choose 1 or 2 : ")
        if choice in ('1', '2'):
            break
        else:
            print("Invalid choice. Please enter 1 or 2.")

    if choice == '1':
      celsius = float(input("Enter temperature in Celsius: "))
      fahrenheit = celsius_to_fahrenheit(celsius)
      print(f"{celsius}°C is equal to {fahrenheit:.2f}°F")

    elif choice == '2':
       fahrenheit = float(input("Enter temperature in Fahrenheit: "))
       celsius = fahrenheit_to_celsius(fahrenheit)
       print(f"{fahrenheit}°F is equal to {celsius:.2f}°C")

if __name__ == "__main__":
    main()